# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    container_name: db
    image: mongo:4
    restart: always
    volumes:
      - ./docker-data/db:/data/db

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:dev
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - mongo
    environment:
      MONGO_URI_DOCKER: "mongodb://mongo:27017/peppermint"
      JWT_SECRET: "ZwfJtS3muY65CaeZ" # This is an example secret
      PORT: 5000
