# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: api-db
    image: mongo:4
    restart: always
    volumes:
    - ./docker-data/db:/data/db

  api:
    container_name: api
    build: .
    volumes:
    - ./:/usr/src/app:cached
    ports:
      - 5000:5000

  client:
    build: ./client
    ports:
    - "80:80"
    container_name: client

