# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: db
    image: mongo:4
    restart: always
    volumes:
    - ./docker-data/db:/data/db

  api:
    container_name: peppermint-api
    build: .
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      - ./:/usr/src/app:cached
      - npm_cache:/root/.npm:delegated
      - node_modules:/usr/src/app/node_modules:delegated
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
    - "80:80"
    container_name: peppermint

volumes:
  npm_cache:
  node_modules: