# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: db
    image: mongo:4
    restart: always
    volumes:
    - ./docker-data/db:/data/db

  client:
    container_name: peppermint
    build: .
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - mongo

networks: 
  local:
    driver: bridge 