version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint


  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    restart: always
    volumes:
      - ./peppermint/db:/data/db
    user: root
    expose:
      - 8025
    ports:
      - 8025:8025
    healthcheck:
      test: echo | telnet 127.0.0.1 1025

  
volumes: 
  pgdata: